language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '14'
script:
  - npm run lint
  - npm run test
  - npm run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
